import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { SessionWrapper } from "./components/SessionWrapper";
import { ContextProvider } from "./context/contextProvider";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Movie Master",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <SessionWrapper>
          <ContextProvider>{children}</ContextProvider>
        </SessionWrapper>
      </body>
    </html>
  );
}
